added starting of docker-compose

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,15 +25,8 @@ jobs:
         pip install pytest
         pip install pylint
 
-    - name: Lint with pylint
-      run: |
-        pylint certification_service > pylint_report.txt || true
-        pylint_exit_code=$?
-        if [ $pylint_exit_code -eq 32 ]; then
-          echo "Pylint found fatal errors, failing..."
-          exit 1
-        fi
-        echo "Pylint completed with exit code: $pylint_exit_code"
+    - name: Start Docker service
+      run: sudo systemctl start docker
 
     - name: Check Docker Compose version
       run: docker-compose version
@@ -51,8 +44,21 @@ jobs:
         until docker-compose exec -T mongodb mongosh --quiet --eval "db.runCommand('ping')"; do
           sleep 2
         done
+
+    - name: Check MongoDB logs on failure
+      if: failure()
+      run: docker-compose logs mongodb
       
-    
     - name: Run tests with docker environment settings of certification_service
       run: |
         docker-compose run --rm app pytest tests/integration/test_database.py
+      
+    - name: Lint with pylint
+      run: |
+        pylint certification_service > pylint_report.txt || true
+        pylint_exit_code=$?
+        if [ $pylint_exit_code -eq 32 ]; then
+          echo "Pylint found fatal errors, failing..."
+          exit 1
+        fi
+        echo "Pylint completed with exit code: $pylint_exit_code"
