github actions tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,8 +40,15 @@ jobs:
           
     - name: Wait for MongoDB to be ready
       run: |
-        # Wait for MongoDB to initialize
-        until docker compose exec -T mongodb mongosh --quiet --eval "db.runCommand('ping')"; do
+        retries=0
+        max_retries=10
+        until docker compose exec -T mongodb mongosh --quiet --eval "db.adminCommand({ ping: 1 })" | grep -q 'ok'; do
+          retries=$((retries+1))
+          if [ $retries -ge $max_retries ]; then
+            echo "MongoDB failed to initialize after $max_retries retries."
+            exit 1
+          fi
+          echo "Waiting for MongoDB to initialize... Retry #$retries"
           sleep 2
         done
 
@@ -49,9 +56,9 @@ jobs:
       if: failure()
       run: docker compose logs mongodb
       
-    - name: Run tests with docker environment settings of certification_service
+    - name: Run tests with test_runner
       run: |
-        docker compose run --rm app pytest tests/integration/test_database.py
+        docker compose run --rm test_runner
       
     - name: Lint with pylint
       run: |
